feat: add path to mutator function
json-schema-tools/traverse pull request #96
Opened 2020-09-04 20:58 UTC by mattbford

fixes #92

2020-09-08 20:25 UTC, mattbford commented
TODO: needs array implementation and then it should be good to go

2020-09-08 22:11 UTC, BelfordZ commented on src/index.ts
> +  pathStack: any[] = [],
```suggestion
  pathStack: string[] = [],
```

2020-09-18 21:55 UTC, BelfordZ commented on src/index.ts
> +const jsonPathStringify = (s: any[]) => {
should this be `s: string[]`?

2020-09-18 22:03 UTC, BelfordZ commented on src/index.ts
> +          pathStack.push(`${i}`);
i.toString(); is preferable over implicit type cast

2020-09-18 22:07 UTC, BelfordZ requested changes
looks great, just a couple nits.

2020-09-21 23:07 UTC, BelfordZ commented on src/index.ts
>    if(depth === 0) {
```suggestion
  if (depth === 0) {
```

hmm linting should have caught this...

2020-09-21 23:08 UTC, BelfordZ approved these changes

2020-09-21 23:12 UTC, merged

2020-09-21 23:15 UTC, BelfordZ commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [GitHub release](https://github.com/json-schema-tools/traverse/releases/tag/1.7.0)
- `1.7.0`
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@json-schema-tools/traverse/v/1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: